-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE DeriveDataTypeable #-}

-- | The abstract syntax of language LF2.

module AbsLF where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Program = Prog [Function]
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data, Typeable)

data Function = Fun Type Ident [Decl] Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data, Typeable)

data Decl = Dec Type Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data, Typeable)

data Exp
    = EIf Exp Exp Exp
    | EOr Exp Exp
    | EAnd Exp Exp
    | ENot Exp
    | ECon Exp Exp
    | EAdd Exp Exp
    | ESub Exp Exp
    | EMul Exp Exp
    | EDiv Exp Exp
    | ECall Ident [Exp]
    | EInt Integer
    | EVar Ident
    | EStr String
    | ETrue
    | EFalse
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data, Typeable)

data Type = Tbool | Tint | TStr | TFun Type [Type]
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data, Typeable)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString, Data, Typeable)

