

module AbsLI where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Read)
data Program = Prog [Function]
  deriving (Eq, Ord, Read)

data Function = Fun Type Ident [Decl] [Stm]
  deriving (Eq, Ord,  Read)

data Decl = Dec Type Ident
  deriving (Eq, Ord, Read)

data Stm
    = SDec Decl
    | SAss Ident Exp
    | SBlock [Stm]
    | SWhile Exp Stm
    | SReturn Exp
    | SIf Exp Stm Stm
  deriving (Eq, Ord, Read)

data Type = Tbool | Tint | Tvoid | TStr | TFun Function
  deriving (Eq, Ord, Read)

data Exp
    = EOr Exp Exp
    | EAnd Exp Exp
    | ENot Exp
    | ECon Exp Exp
    | EAdd Exp Exp
    | ESub Exp Exp
    | EMul Exp Exp
    | EDiv Exp Exp
    | Call Ident [Exp]
    | EInt Integer
    | EVar Ident
    | EStr String
    | ETrue
    | EFalse
  deriving (Eq, Ord,  Read)

